from typing import Any, Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictStr,
    field_validator,
    model_validator,
)

from app.schemas.page_content import PageContentWorkspaceResponse, SearchUpdateReceipt


MIN_ORDER_VALUE = -2147483648
MAX_ORDER_VALUE = 2147483647

# Rust-compatible regex patterns.
# No lookahead / lookbehind.
CLEAN_TEXT_PATTERN = r"^[^\x00-\x20\x7F][^\x00-\x1F\x7F]*$"
CLEAN_DOCUMENT_ID_PATTERN = r"^[^\x00-\x20\x7F]+$"


# ---------------------------------------------------------
# Base config helpers
# ---------------------------------------------------------

class StrictRequestModel(BaseModel):
    """
    Base model for request bodies.

    extra="forbid" rejects unknown/random fields generated by fuzzing.
    """
    model_config = ConfigDict(extra="forbid")


# ---------------------------------------------------------
# Reusable validation helpers
# ---------------------------------------------------------

def validate_order_not_bool(value: Any) -> Any:
    """
    Reject booleans for order.

    Important:
    - OpenAPI should still expose order as normal integer with min/max.
    - Pydantic should still reject true/false.
    """
    if isinstance(value, bool):
        raise ValueError("Order must be an integer, not a boolean")

    return value


# ---------------------------------------------------------
# Access control schemas
# ---------------------------------------------------------

class AccessRoleResponse(BaseModel):
    name: StrictStr
    scope: StrictStr
    program: StrictStr = ""
    function: StrictStr = ""


class AccessUserResponse(BaseModel):
    email: StrictStr


class AccessGroupResponse(BaseModel):
    roles: list[AccessRoleResponse] = Field(default_factory=list)
    users: list[AccessUserResponse] = Field(default_factory=list)


class AccessControlResponse(BaseModel):
    admins: AccessGroupResponse = Field(default_factory=AccessGroupResponse)
    viewers: AccessGroupResponse = Field(default_factory=AccessGroupResponse)


# ---------------------------------------------------------
# Tab response schemas
# ---------------------------------------------------------

class TabParentResponse(BaseModel):
    id: int | None = None
    documentId: StrictStr | None = None
    title: StrictStr | None = None
    order: int = 0


class TabSummaryResponse(BaseModel):
    id: int | None = None
    documentId: StrictStr | None = None
    title: StrictStr | None = None
    order: int = 0

    locked: StrictBool = False
    locked_by: StrictStr = ""

    has_children: StrictBool = False
    has_content: StrictBool = False

    # True if this tab has one or more "tab variants" (TabV2.parent_tab_id
    # children — a distinct nesting axis from has_children above, which
    # reflects gridstack-level nesting). v2 only, always False for v1.
    has_variants: StrictBool = False

    # Included so a variant-listing caller can pre-populate ManageAccessModal
    # without an extra fetch; omitted (None) by callers that don't need it.
    access_control: AccessControlResponse | dict[str, Any] | None = None

    # Populated for root tabs only (v2). Lets the mirror picker group roots
    # by dashboard and disambiguates two roots that share a title across
    # different nav tabs. None for sub-tabs, variants, and v1 tabs.
    navTabDocumentId: StrictStr | None = None
    navTabTitle: StrictStr | None = None

    # Which backend/schema this tab lives in — 'v1' (default, the original
    # schema) or 'v2' (the normalized tabs/gridstacks/components schema).
    # Tells the frontend which API base path (/tabs vs /v2/tabs) to use for
    # any further operation on this tab. Not to be confused with
    # GridCanvasContent.schemaVersion (the JSONB content-shape version).
    apiVersion: Literal["v1", "v2"] = "v1"

    # Empty for reads; populated by v2 mutations after their DB commit.
    search_updates: list[SearchUpdateReceipt] = Field(default_factory=list)


class TabWorkspaceResponse(BaseModel):
    id: int | None = None
    documentId: StrictStr | None = None
    title: StrictStr | None = None
    order: int = 0

    parent: TabParentResponse | None = None
    page_content: PageContentWorkspaceResponse | None = None

    # Allows normalized DB rows that may return a plain dict. Nullable: a
    # v2 SBN node's access_control is None on the wire whenever it means
    # "inherit" (§3.4/§5.2's NULL-through fix, get_sbn_workspace) rather
    # than a manufactured default -- this field being non-nullable was a
    # latent bug (pre-existing, session 6) that 500'd this response model
    # for exactly that case; no test caught it because the engine-level
    # test called get_sbn_workspace directly, bypassing response
    # validation. Found while adding resolved_parent_access_control (commit
    # 8a) and its test, which is the first thing to exercise this through
    # the actual HTTP router.
    access_control: AccessControlResponse | dict[str, Any] | None = Field(
        default_factory=AccessControlResponse
    )

    # Populated by get_tab_workspace_v2 (v2 root/variant/sub-tab reads): this
    # node's own EFFECTIVE access_control, resolved past any NULL ancestors
    # (landmine 14) -- also the exact ceiling a canvas widget sitting on
    # this node is validated against (§3.4). None for v1 / callers that
    # don't resolve it.
    resolved_access_control: AccessControlResponse | dict[str, Any] | None = None

    # Populated by get_sbn_workspace (v2 SBN node reads) only: the ceiling
    # THIS node's own access_control is validated against on write (§3.4) --
    # its resolved PARENT's effective AC, not its own. None for every other
    # caller of this shape (a tab/sub-tab is a propagating tab-family node,
    # not itself subset-constrained, so it has no such ceiling).
    resolved_parent_access_control: AccessControlResponse | dict[str, Any] | None = None

    locked: StrictBool = False
    locked_by: StrictStr = ""

    children: list[TabSummaryResponse] = Field(default_factory=list)

    has_variants: StrictBool = False

    apiVersion: Literal["v1", "v2"] = "v1"

    # Empty for reads; populated by v2 mutations after their DB commit.
    search_updates: list[SearchUpdateReceipt] = Field(default_factory=list)


class BreadcrumbItemResponse(BaseModel):
    id: int | None = None
    documentId: StrictStr | None = None
    title: StrictStr | None = None
    order: int = 0


# ---------------------------------------------------------
# Nav tab response schemas
# ---------------------------------------------------------

class NavTabResponse(BaseModel):
    id: int | None = None
    documentId: StrictStr | None = None
    slug: StrictStr | None = None
    title: StrictStr | None = None
    order: int = 0

    access_control: AccessControlResponse | dict[str, Any] | None = None

    protected: StrictBool = False

    # Empty for reads; populated by mutations after their DB commit.
    search_updates: list[SearchUpdateReceipt] = Field(default_factory=list)


class NavTabListAPIResponse(BaseModel):
    data: list[NavTabResponse] = Field(default_factory=list)


# ---------------------------------------------------------
# Standard API wrapper responses
# ---------------------------------------------------------

class TabSummaryListAPIResponse(BaseModel):
    data: list[TabSummaryResponse] = Field(default_factory=list)


class TabWorkspaceAPIResponse(BaseModel):
    data: TabWorkspaceResponse


class BreadcrumbAPIResponse(BaseModel):
    data: list[BreadcrumbItemResponse] = Field(default_factory=list)


# ---------------------------------------------------------
# Request schemas
# ---------------------------------------------------------

class CreateTabRequest(StrictRequestModel):
    title: StrictStr = Field(
        min_length=1,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    parentDocumentId: StrictStr | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        pattern=CLEAN_DOCUMENT_ID_PATTERN,
    )

    content: dict[str, Any] | list[Any] | None = None

    order: int | None = Field(
        default=None,
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    # IMPORTANT:
    # The frontend sends inherited access_control when creating a tab.
    # Without this field, FastAPI rejects the request with 422.
    access_control: AccessControlResponse | dict[str, Any] | None = None

    # Which nav tab a new ROOT tab belongs to. Ignored for a sub-tab create
    # (parentDocumentId set) — sub-tabs have no nav_tab_id of their own. When
    # absent for a root create, the router falls back to the Dashboard nav
    # tab so any existing caller keeps working unchanged.
    navTabDocumentId: StrictStr | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        pattern=CLEAN_DOCUMENT_ID_PATTERN,
    )

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class UpdateTabRequest(StrictRequestModel):
    title: StrictStr | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    order: int | None = Field(
        default=None,
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    access_control: AccessControlResponse | dict[str, Any] | None = None

    locked: StrictBool | None = None

    locked_by: StrictStr | None = Field(
        default=None,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class CreateTabVariantRequest(StrictRequestModel):
    title: StrictStr = Field(
        min_length=1,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    access_control: AccessControlResponse | dict[str, Any] | None = None

    order: int | None = Field(
        default=None,
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class ReorderTabVariantsRequest(StrictRequestModel):
    orderedDocumentIds: list[StrictStr] = Field(default_factory=list)


class MoveTabRequest(StrictRequestModel):
    newParentDocumentId: StrictStr | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        pattern=CLEAN_DOCUMENT_ID_PATTERN,
    )

    order: int | None = Field(
        default=None,
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class ReorderTabItemRequest(StrictRequestModel):
    documentId: StrictStr = Field(
        min_length=1,
        max_length=255,
        pattern=CLEAN_DOCUMENT_ID_PATTERN,
    )

    order: int = Field(
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class ReorderTabsRequest(StrictRequestModel):
    items: list[ReorderTabItemRequest] = Field(min_length=1)


class UpdateTabContentRequest(StrictRequestModel):
    content: dict[str, Any] | list[Any] | None = None


class LockTabRequest(StrictRequestModel):
    locked_by: StrictStr = Field(
        min_length=1,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )


class UnlockTabRequest(StrictRequestModel):
    unlocked_by: StrictStr | None = Field(
        default=None,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    force: StrictBool = False


# ---------------------------------------------------------
# Nav tab request schemas
# ---------------------------------------------------------

class CreateNavTabRequest(StrictRequestModel):
    title: StrictStr = Field(
        min_length=1,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    access_control: AccessControlResponse | dict[str, Any] | None = None

    order: int | None = Field(
        default=None,
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class UpdateNavTabRequest(StrictRequestModel):
    title: StrictStr | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    order: int | None = Field(
        default=None,
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    access_control: AccessControlResponse | dict[str, Any] | None = None

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class ReorderNavTabsRequest(StrictRequestModel):
    orderedDocumentIds: list[StrictStr] = Field(default_factory=list)


class MoveTabToNavTabRequest(StrictRequestModel):
    navTabDocumentId: StrictStr = Field(
        min_length=1,
        max_length=255,
        pattern=CLEAN_DOCUMENT_ID_PATTERN,
    )


# ---------------------------------------------------------
# Hub schemas (phase 2, §5.4) — one row, no title/slug of its own.
# ---------------------------------------------------------

class HubResponse(BaseModel):
    documentId: StrictStr | None = None
    title: StrictStr = "Hub"
    access_control: AccessControlResponse | dict[str, Any] | None = None


class HubAPIResponse(BaseModel):
    data: HubResponse


class UpdateHubRequest(StrictRequestModel):
    access_control: AccessControlResponse | dict[str, Any] | None = None


# ---------------------------------------------------------
# Preview / purge / reset schemas (§5.4, §5.5, §6.3, §6.4) — shared across
# the hub, nav-tab, and tab routers; none of the three surfaces need their
# own request shape beyond "which access_control would be written" or
# "which principal to strip".
# ---------------------------------------------------------

class PreviewAccessWriteRequest(StrictRequestModel):
    """Backs POST .../access/preview on all three routers (hub, nav tab,
    tab). Read-only — plan_write is never applied from this request."""
    access_control: AccessControlResponse | dict[str, Any] | None = None


class PrincipalRequest(StrictRequestModel):
    """A user or a role, named by type rather than by which group (admins
    vs viewers) it currently sits in — purge strips a principal from both,
    wherever it's found."""
    type: Literal["user", "role"]
    email: StrictStr | None = None
    name: StrictStr | None = None
    scope: StrictStr = ""
    program: StrictStr = ""
    function: StrictStr = ""

    @model_validator(mode="after")
    def _check_required_field(self) -> "PrincipalRequest":
        if self.type == "user" and not self.email:
            raise ValueError("email is required when type is 'user'")
        if self.type == "role" and not self.name:
            raise ValueError("name is required when type is 'role'")
        return self


class PurgePrincipalRequest(StrictRequestModel):
    principal: PrincipalRequest
