from typing import Any, Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictStr,
    field_validator,
    model_validator,
)

from app.schemas.page_content import PageContentWorkspaceResponse, SearchUpdateReceipt


MIN_ORDER_VALUE = -2147483648
MAX_ORDER_VALUE = 2147483647

# Rust-compatible regex patterns.
# No lookahead / lookbehind.
CLEAN_TEXT_PATTERN = r"^[^\x00-\x20\x7F][^\x00-\x1F\x7F]*$"
CLEAN_DOCUMENT_ID_PATTERN = r"^[^\x00-\x20\x7F]+$"

# A lucide-react icon name (e.g. "layout-grid") — a lookup key only, never
# checked against the icon library itself. Deliberately not an allowlist of
# every registered name: that would need a generated constant kept in sync
# with every lucide-react bump, and buys nothing, since an unknown name just
# degrades to the fallback icon client-side (see NavTabV2.icon's docstring).
ICON_NAME_PATTERN = r"^[a-z0-9]+(-[a-z0-9]+)*$"


# ---------------------------------------------------------
# Base config helpers
# ---------------------------------------------------------

class StrictRequestModel(BaseModel):
    """
    Base model for request bodies.

    extra="forbid" rejects unknown/random fields generated by fuzzing.
    """
    model_config = ConfigDict(extra="forbid")


# ---------------------------------------------------------
# Reusable validation helpers
# ---------------------------------------------------------

def validate_order_not_bool(value: Any) -> Any:
    """
    Reject booleans for order.

    Important:
    - OpenAPI should still expose order as normal integer with min/max.
    - Pydantic should still reject true/false.
    """
    if isinstance(value, bool):
        raise ValueError("Order must be an integer, not a boolean")

    return value


# ---------------------------------------------------------
# Access control schemas
# ---------------------------------------------------------

class AccessRoleResponse(BaseModel):
    name: StrictStr
    scope: StrictStr
    program: StrictStr = ""
    function: StrictStr = ""


class AccessUserResponse(BaseModel):
    email: StrictStr


class AccessGroupResponse(BaseModel):
    roles: list[AccessRoleResponse] = Field(default_factory=list)
    users: list[AccessUserResponse] = Field(default_factory=list)


class AccessControlResponse(BaseModel):
    admins: AccessGroupResponse = Field(default_factory=AccessGroupResponse)
    viewers: AccessGroupResponse = Field(default_factory=AccessGroupResponse)


# ---------------------------------------------------------
# Tab response schemas
# ---------------------------------------------------------

class TabParentResponse(BaseModel):
    id: int | None = None
    documentId: StrictStr | None = None
    title: StrictStr | None = None
    order: int = 0


class TabSummaryResponse(BaseModel):
    id: int | None = None
    documentId: StrictStr | None = None
    title: StrictStr | None = None
    order: int = 0

    locked: StrictBool = False
    locked_by: StrictStr = ""

    has_children: StrictBool = False
    has_content: StrictBool = False

    # True if this tab has one or more "tab variants" (TabV2.parent_tab_id
    # children — a distinct nesting axis from has_children above, which
    # reflects gridstack-level nesting). v2 only, always False for v1.
    has_variants: StrictBool = False

    # Included so a variant-listing caller can pre-populate ManageAccessModal
    # without an extra fetch; omitted (None) by callers that don't need it.
    access_control: AccessControlResponse | dict[str, Any] | None = None

    # Populated for root tabs only (v2). Lets the mirror picker group roots
    # by dashboard and disambiguates two roots that share a title across
    # different nav tabs. None for sub-tabs, variants, and v1 tabs.
    navTabDocumentId: StrictStr | None = None
    navTabTitle: StrictStr | None = None

    # Which backend/schema this tab lives in — 'v1' (default, the original
    # schema) or 'v2' (the normalized tabs/gridstacks/components schema).
    # Tells the frontend which API base path (/tabs vs /v2/tabs) to use for
    # any further operation on this tab. Not to be confused with
    # GridCanvasContent.schemaVersion (the JSONB content-shape version).
    apiVersion: Literal["v1", "v2"] = "v1"

    # Empty for reads; populated by v2 mutations after their DB commit.
    search_updates: list[SearchUpdateReceipt] = Field(default_factory=list)


class TabWorkspaceResponse(BaseModel):
    id: int | None = None
    documentId: StrictStr | None = None
    title: StrictStr | None = None
    order: int = 0

    parent: TabParentResponse | None = None
    page_content: PageContentWorkspaceResponse | None = None

    # Allows normalized DB rows that may return a plain dict. Nullable: a
    # v2 SBN node's access_control is None on the wire whenever nothing has
    # been set on it (get_sbn_workspace) rather than a manufactured
    # default -- this field being non-nullable was a latent bug
    # (pre-existing, session 6) that 500'd this response model for exactly
    # that case.
    access_control: AccessControlResponse | dict[str, Any] | None = Field(
        default_factory=AccessControlResponse
    )

    locked: StrictBool = False
    locked_by: StrictStr = ""

    children: list[TabSummaryResponse] = Field(default_factory=list)

    has_variants: StrictBool = False

    apiVersion: Literal["v1", "v2"] = "v1"

    # Empty for reads; populated by v2 mutations after their DB commit.
    search_updates: list[SearchUpdateReceipt] = Field(default_factory=list)


class BreadcrumbItemResponse(BaseModel):
    id: int | None = None
    documentId: StrictStr | None = None
    title: StrictStr | None = None
    order: int = 0


# ---------------------------------------------------------
# Nav tab response schemas
# ---------------------------------------------------------

class NavTabResponse(BaseModel):
    id: int | None = None
    documentId: StrictStr | None = None
    slug: StrictStr | None = None
    title: StrictStr | None = None
    order: int = 0

    access_control: AccessControlResponse | dict[str, Any] | None = None

    protected: StrictBool = False

    icon: StrictStr | None = None

    # Empty for reads; populated by mutations after their DB commit.
    search_updates: list[SearchUpdateReceipt] = Field(default_factory=list)


class NavTabListAPIResponse(BaseModel):
    data: list[NavTabResponse] = Field(default_factory=list)


# ---------------------------------------------------------
# Standard API wrapper responses
# ---------------------------------------------------------

class TabSummaryListAPIResponse(BaseModel):
    data: list[TabSummaryResponse] = Field(default_factory=list)


class TabWorkspaceAPIResponse(BaseModel):
    data: TabWorkspaceResponse


class BreadcrumbAPIResponse(BaseModel):
    data: list[BreadcrumbItemResponse] = Field(default_factory=list)


# ---------------------------------------------------------
# Request schemas
# ---------------------------------------------------------

class CreateTabRequest(StrictRequestModel):
    title: StrictStr = Field(
        min_length=1,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    parentDocumentId: StrictStr | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        pattern=CLEAN_DOCUMENT_ID_PATTERN,
    )

    content: dict[str, Any] | list[Any] | None = None

    order: int | None = Field(
        default=None,
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    # IMPORTANT:
    # The frontend sends inherited access_control when creating a tab.
    # Without this field, FastAPI rejects the request with 422.
    access_control: AccessControlResponse | dict[str, Any] | None = None

    # Which nav tab a new ROOT tab belongs to. Ignored for a sub-tab create
    # (parentDocumentId set) — sub-tabs have no nav_tab_id of their own. When
    # absent for a root create, the router falls back to the Dashboard nav
    # tab so any existing caller keeps working unchanged.
    navTabDocumentId: StrictStr | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        pattern=CLEAN_DOCUMENT_ID_PATTERN,
    )

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class UpdateTabRequest(StrictRequestModel):
    title: StrictStr | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    order: int | None = Field(
        default=None,
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    access_control: AccessControlResponse | dict[str, Any] | None = None

    locked: StrictBool | None = None

    locked_by: StrictStr | None = Field(
        default=None,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class CreateTabVariantRequest(StrictRequestModel):
    title: StrictStr = Field(
        min_length=1,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    access_control: AccessControlResponse | dict[str, Any] | None = None

    order: int | None = Field(
        default=None,
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class ReorderTabVariantsRequest(StrictRequestModel):
    orderedDocumentIds: list[StrictStr] = Field(default_factory=list)


class MoveTabRequest(StrictRequestModel):
    newParentDocumentId: StrictStr | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        pattern=CLEAN_DOCUMENT_ID_PATTERN,
    )

    order: int | None = Field(
        default=None,
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class ReorderTabItemRequest(StrictRequestModel):
    documentId: StrictStr = Field(
        min_length=1,
        max_length=255,
        pattern=CLEAN_DOCUMENT_ID_PATTERN,
    )

    order: int = Field(
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class ReorderTabsRequest(StrictRequestModel):
    items: list[ReorderTabItemRequest] = Field(min_length=1)


class UpdateTabContentRequest(StrictRequestModel):
    content: dict[str, Any] | list[Any] | None = None


class UpdateComponentContentRequest(StrictRequestModel):
    """Body of the per-component content write (§6.7 of
    plan_access_control_algorithm_2026-08-27.md).

    Partial: only the fields actually present are applied — the router reads
    `model_fields_set` — so a caller can rename a widget without resending
    its whole data blob.

    WHAT IS ABSENT IS THE INTERESTING PART, and `extra="forbid"` (inherited
    from StrictRequestModel) is what makes the absences enforceable rather
    than merely conventional:

      * `x`/`y`/`w`/`h` — repositioning is DELIBERATELY not implemented;
        §11.3 defers it pending team discussion.
      * `access_control` — authorization, not content. Grants are edited
        through the grants surface, which has its own gate (§6.3).
      * `type`, `link` — a type change re-interprets the stored blob, and
        `type` is the only route by which the `restricted` redaction
        sentinel could reach `components.type`. A client that posts a whole
        serialized widget entry therefore gets a 422 instead of a partial
        write, which is the intended outcome: that body was built for the
        canvas save, and the canvas save is exactly what §6.7 says a
        component-scoped editor must not use.

    See `gridstack_service.update_component_content` for the full rationale.
    """

    title: StrictStr | None = Field(default=None, max_length=255)
    description: StrictStr | None = None

    # Nullable in the ANNOTATION so an absent key is representable, but an
    # EXPLICIT null is refused below. See `_reject_explicit_null_data`.
    data: dict[str, Any] | None = None

    @model_validator(mode="after")
    def _reject_explicit_null_data(self) -> "UpdateComponentContentRequest":
        """`data: null` is a 422, while an omitted `data` means "leave it
        alone" and `data: {}` means "empty this widget".

        THIS IS THE SECOND HALF OF THE SENTINEL GUARD. A widget the caller
        may not see is served as `{"type": "restricted", "data": null}`
        (tab_service.py:100), and that entry KEEPS ITS KEY, so it round-trips
        through a stale client and comes back on the next save. `type` is
        already refused by `extra="forbid"`; `data: null` is the other half
        of that same body. Accepting it would overwrite a real widget's
        stored content with `{}` — the precise data-loss path the canvas save
        was fixed for on 2026-08-30, rebuilt on a new door.

        Refusing rather than ignoring, because unlike the canvas save there
        is nothing to degrade gracefully FOR here: this endpoint edits one
        component the caller named explicitly, so a null blob is a
        malformed request about that component, not an incidental sibling
        entry that can be skipped. "Clear this widget" stays expressible as
        `data: {}`.
        """
        if "data" in self.model_fields_set and self.data is None:
            raise ValueError(
                "data must be an object; send {} to empty the widget, or omit "
                "the field to leave it unchanged"
            )
        return self


class LockTabRequest(StrictRequestModel):
    locked_by: StrictStr = Field(
        min_length=1,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )


class UnlockTabRequest(StrictRequestModel):
    unlocked_by: StrictStr | None = Field(
        default=None,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    force: StrictBool = False


# ---------------------------------------------------------
# Nav tab request schemas
# ---------------------------------------------------------

class CreateNavTabRequest(StrictRequestModel):
    title: StrictStr = Field(
        min_length=1,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    access_control: AccessControlResponse | dict[str, Any] | None = None

    order: int | None = Field(
        default=None,
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    icon: StrictStr | None = Field(default=None, max_length=64, pattern=ICON_NAME_PATTERN)

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class UpdateNavTabRequest(StrictRequestModel):
    title: StrictStr | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    order: int | None = Field(
        default=None,
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    access_control: AccessControlResponse | dict[str, Any] | None = None

    # Three-way, like the airtable `pat` field: omitted (leave alone, checked
    # via model_fields_set at the router) vs. present-and-a-string (set) vs.
    # present-and-null (clear to the default icon — §3.4's "Use default").
    icon: StrictStr | None = Field(default=None, max_length=64, pattern=ICON_NAME_PATTERN)

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class ReorderNavTabsRequest(StrictRequestModel):
    orderedDocumentIds: list[StrictStr] = Field(default_factory=list)


class MoveTabToNavTabRequest(StrictRequestModel):
    navTabDocumentId: StrictStr = Field(
        min_length=1,
        max_length=255,
        pattern=CLEAN_DOCUMENT_ID_PATTERN,
    )
