from datetime import datetime
from typing import Any, Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictStr,
    field_validator,
    model_validator,
)

from app.schemas.page_content import PageContentWorkspaceResponse, SearchUpdateReceipt


MIN_ORDER_VALUE = -2147483648
MAX_ORDER_VALUE = 2147483647

# Rust-compatible regex patterns.
# No lookahead / lookbehind.
CLEAN_TEXT_PATTERN = r"^[^\x00-\x20\x7F][^\x00-\x1F\x7F]*$"
CLEAN_DOCUMENT_ID_PATTERN = r"^[^\x00-\x20\x7F]+$"

# A lucide-react icon name (e.g. "layout-grid") — a lookup key only, never
# checked against the icon library itself. Deliberately not an allowlist of
# every registered name: that would need a generated constant kept in sync
# with every lucide-react bump, and buys nothing, since an unknown name just
# degrades to the fallback icon client-side (see NavTabV2.icon's docstring).
ICON_NAME_PATTERN = r"^[a-z0-9]+(-[a-z0-9]+)*$"


# ---------------------------------------------------------
# Base config helpers
# ---------------------------------------------------------

class StrictRequestModel(BaseModel):
    """
    Base model for request bodies.

    extra="forbid" rejects unknown/random fields generated by fuzzing.
    """
    model_config = ConfigDict(extra="forbid")


# ---------------------------------------------------------
# Reusable validation helpers
# ---------------------------------------------------------

def validate_order_not_bool(value: Any) -> Any:
    """
    Reject booleans for order.

    Important:
    - OpenAPI should still expose order as normal integer with min/max.
    - Pydantic should still reject true/false.
    """
    if isinstance(value, bool):
        raise ValueError("Order must be an integer, not a boolean")

    return value


# ---------------------------------------------------------
# Access control schemas
# ---------------------------------------------------------

class AccessRoleResponse(BaseModel):
    name: StrictStr
    scope: StrictStr
    program: StrictStr = ""
    function: StrictStr = ""


class AccessUserResponse(BaseModel):
    email: StrictStr


class AccessGroupResponse(BaseModel):
    roles: list[AccessRoleResponse] = Field(default_factory=list)
    users: list[AccessUserResponse] = Field(default_factory=list)


class AccessControlResponse(BaseModel):
    admins: AccessGroupResponse = Field(default_factory=AccessGroupResponse)
    viewers: AccessGroupResponse = Field(default_factory=AccessGroupResponse)


# ---------------------------------------------------------
# Tab response schemas
# ---------------------------------------------------------

class TabParentResponse(BaseModel):
    id: int | None = None
    documentId: StrictStr | None = None
    title: StrictStr | None = None
    order: int = 0


class TabSummaryResponse(BaseModel):
    id: int | None = None
    documentId: StrictStr | None = None
    title: StrictStr | None = None
    order: int = 0

    # plan_access_control_algorithm_2026-08-27.md §5.2's triple —
    # server-computed, never re-derived on the client. `revealed = view and
    # not granted`: the node appears and opens, but its own payload is
    # filtered to (usually) nothing but the child that earned the reveal.
    # All three are None when the caller (an internal mutation-response
    # echo, not a read endpoint) built this summary without a ViewerAccess
    # — see gridstack_service._format_tab_summary's own `access` parameter.
    # A read endpoint always supplies one, so they are never None there.
    view: bool | None = None
    edit: bool | None = None
    revealed: bool | None = None
    # `seed_edit(n)` — added 2026-09-07 (edit-mode-gap follow-up), alongside
    # the §5.2 triple above but not part of it (see NodeVerdict.edit_seed).
    # TRUE iff a resource_grant is written DIRECTLY on this node, regardless
    # of whether an ancestor's grant also makes `edit` True. Drives pencil
    # placement client-side — replaces the old client-derived
    # `isEditFrontier(edit, parentEdit)` approximation, which could not tell
    # "no grant of my own" apart from "my own grant that an ancestor's
    # grant also happens to cover". None under the same conditions as the
    # triple above (no `access` passed).
    edit_seed: bool | None = None

    locked: StrictBool = False
    locked_by: StrictStr = ""
    # plan §6.6 Fix 2. `locked_at` is None for an unlocked tab AND for a
    # locked one with no timestamp (every lock taken before this column
    # existed — see TabV2.locked_at's own comment); `lock_is_stale` is
    # server-computed (is_lock_stale in gridstack_service.py) rather than
    # left for the client to re-derive from `locked_at` + a TTL it would
    # have to know separately — always False when `locked` is False.
    locked_at: datetime | None = None
    lock_is_stale: StrictBool = False

    # plan_lock_propagation_2026-09-08.md §4.3 — ADDITIVE. The four fields
    # above keep their exact existing meaning (this node's own row); these
    # four are new and DERIVED across the whole ancestor/descendant chain
    # (edit_lock_service.LockView.state_for), so no existing read path
    # breaks mid-migration. `lock_state` is None under the same conditions
    # `view`/`edit`/`revealed` above are — an internal mutation-response
    # echo built with no LockView, never a real read endpoint.
    lock_state: Literal["free", "self", "locked_here", "locked_by_ancestor", "blocked_by_descendant"] | None = None
    lock_holder: StrictStr = ""
    lock_holder_node_label: StrictStr = ""
    lock_expires_at: datetime | None = None

    has_children: StrictBool = False
    has_content: StrictBool = False

    # True if this tab has one or more "tab variants" (TabV2.parent_tab_id
    # children — a distinct nesting axis from has_children above, which
    # reflects gridstack-level nesting). v2 only, always False for v1.
    has_variants: StrictBool = False

    # Included so a variant-listing caller can pre-populate ManageAccessModal
    # without an extra fetch; omitted (None) by callers that don't need it.
    access_control: AccessControlResponse | dict[str, Any] | None = None

    # Populated for root tabs only (v2). Lets the mirror picker group roots
    # by dashboard and disambiguates two roots that share a title across
    # different nav tabs. None for sub-tabs, variants, and v1 tabs.
    navTabDocumentId: StrictStr | None = None
    navTabTitle: StrictStr | None = None

    # Which backend/schema this tab lives in — 'v1' (default, the original
    # schema) or 'v2' (the normalized tabs/gridstacks/components schema).
    # Tells the frontend which API base path (/tabs vs /v2/tabs) to use for
    # any further operation on this tab. Not to be confused with
    # GridCanvasContent.schemaVersion (the JSONB content-shape version).
    apiVersion: Literal["v1", "v2"] = "v1"

    # The resource_grants node (plan_access_control_algorithm_2026-08-27.md
    # §9) this row's "Manage Access" should actually edit — the same NodeRef
    # `resolve_gridstack_node` already resolves to produce view/edit/revealed
    # above, just also serialized. For a root tab or variant this equals
    # `("tab", self.id)`; for a nested SGS sub-tab it is the SUB-GRID'S
    # REPRESENTATION COMPONENT (§3.1), a different id than `id` above, which
    # for a sub-tab is the gridstack's own id — there was previously no way
    # for the frontend to resolve one from the other. `None` for v1 tabs
    # (no resource_grants equivalent exists) and for an orphaned v2 row
    # (§3.3 fail-closed). Independent of `access` — populated on every read,
    # including internal mutation-response echoes that pass none.
    node_kind: Literal["hub", "nav_tab", "tab", "component"] | None = None
    node_id: int | None = None

    # Empty for reads; populated by v2 mutations after their DB commit.
    search_updates: list[SearchUpdateReceipt] = Field(default_factory=list)


class TabWorkspaceResponse(BaseModel):
    id: int | None = None
    documentId: StrictStr | None = None
    title: StrictStr | None = None
    order: int = 0

    # See TabSummaryResponse's identical fields for what these mean. Absence
    # of `view=True` here for a real tab is impossible from a read endpoint
    # — an invisible node's workspace 404s instead (plan §9).
    view: bool | None = None
    edit: bool | None = None
    revealed: bool | None = None
    edit_seed: bool | None = None

    parent: TabParentResponse | None = None
    page_content: PageContentWorkspaceResponse | None = None

    # Allows normalized DB rows that may return a plain dict. Nullable: a
    # v2 SBN node's access_control is None on the wire whenever nothing has
    # been set on it (get_sbn_workspace) rather than a manufactured
    # default -- this field being non-nullable was a latent bug
    # (pre-existing, session 6) that 500'd this response model for exactly
    # that case.
    access_control: AccessControlResponse | dict[str, Any] | None = Field(
        default_factory=AccessControlResponse
    )

    locked: StrictBool = False
    locked_by: StrictStr = ""
    locked_at: datetime | None = None
    lock_is_stale: StrictBool = False

    # See TabSummaryResponse's identical fields for what these mean.
    lock_state: Literal["free", "self", "locked_here", "locked_by_ancestor", "blocked_by_descendant"] | None = None
    lock_holder: StrictStr = ""
    lock_holder_node_label: StrictStr = ""
    lock_expires_at: datetime | None = None

    # plan_lock_propagation_2026-09-08.md §4.1 — "return the token +
    # expires_at". SENSITIVE, and deliberately narrow: populated ONLY by
    # `lock_tab_by_document_id_v2`'s own response (the one place a caller
    # who just acquired a session needs to learn their own token so they
    # can present it back via `X-Edit-Tokens`), never by an ordinary
    # workspace GET or any other write's echo — this field must never leak
    # a token to a caller who merely has VIEW access to the tab. None
    # everywhere else, matching every other "only when this specific
    # caller populates it" field in this schema.
    lock_token: StrictStr | None = None

    children: list[TabSummaryResponse] = Field(default_factory=list)

    has_variants: StrictBool = False

    apiVersion: Literal["v1", "v2"] = "v1"

    # See TabSummaryResponse's identical fields for what these mean.
    node_kind: Literal["hub", "nav_tab", "tab", "component"] | None = None
    node_id: int | None = None

    # Empty for reads; populated by v2 mutations after their DB commit.
    search_updates: list[SearchUpdateReceipt] = Field(default_factory=list)


class BreadcrumbItemResponse(BaseModel):
    id: int | None = None
    documentId: StrictStr | None = None
    title: StrictStr | None = None
    order: int = 0


# ---------------------------------------------------------
# Nav tab response schemas
# ---------------------------------------------------------

class NavTabResponse(BaseModel):
    id: int | None = None
    documentId: StrictStr | None = None
    slug: StrictStr | None = None
    title: StrictStr | None = None
    order: int = 0

    # See TabSummaryResponse's identical fields for what these mean.
    view: bool | None = None
    edit: bool | None = None
    revealed: bool | None = None

    access_control: AccessControlResponse | dict[str, Any] | None = None

    protected: StrictBool = False

    icon: StrictStr | None = None

    # plan_lock_propagation_2026-09-08.md §1/§3.1 decision 3 — a nav tab is
    # now a real lock node (its edit-mode toggle acquires an actual lock,
    # §6.7), not just an AC one. Own-row fields, new here (nav tabs had no
    # lock columns at all before this plan) but the SAME shape/meaning as
    # TabSummaryResponse's identical four; the four after them are the same
    # additive derived state described there.
    locked: StrictBool = False
    locked_by: StrictStr = ""
    locked_at: datetime | None = None
    lock_is_stale: StrictBool = False

    lock_state: Literal["free", "self", "locked_here", "locked_by_ancestor", "blocked_by_descendant"] | None = None
    lock_holder: StrictStr = ""
    lock_holder_node_label: StrictStr = ""
    lock_expires_at: datetime | None = None

    # plan_lock_propagation_2026-09-08.md §8 phase 5 — SAME sensitive,
    # narrow-population field as TabWorkspaceResponse.lock_token above (see
    # that field's own comment): populated ONLY by
    # `lock_nav_tab_by_document_id_v2`'s own response, never by an ordinary
    # nav-tab list/read or any other write's echo. None everywhere else.
    lock_token: StrictStr | None = None

    # See TabSummaryResponse's identical fields — a nav tab maps straight to
    # its own node (`("nav_tab", self.id)`), no gridstack indirection to
    # resolve, unlike a tab/sub-grid.
    node_kind: Literal["hub", "nav_tab", "tab", "component"] | None = None
    node_id: int | None = None

    # Empty for reads; populated by mutations after their DB commit.
    search_updates: list[SearchUpdateReceipt] = Field(default_factory=list)


class NavTabListAPIResponse(BaseModel):
    data: list[NavTabResponse] = Field(default_factory=list)
    # findings_dev_login_live_testing_2026-09-12.md #4: the ONE signal the
    # frontend had no channel for — "do I hold edit(hub)" — needed to gate
    # nav-tab Delete/reorder correctly (§6.3: both are edit(parent(n)), a
    # STRICTER gate than the plain edit(n) every `NavTabResponse.edit`
    # already carries per row, which only ever answers for that one row).
    # Sits on the list envelope, not per-row, since it is one caller-wide
    # fact about the Hub, not something that varies row to row — and
    # useNavTabs.ts already fetches this same list, so no second request.
    hub_edit: bool = False


# ---------------------------------------------------------
# Standard API wrapper responses
# ---------------------------------------------------------

class TabSummaryListAPIResponse(BaseModel):
    data: list[TabSummaryResponse] = Field(default_factory=list)


class TabWorkspaceAPIResponse(BaseModel):
    data: TabWorkspaceResponse


class BreadcrumbAPIResponse(BaseModel):
    data: list[BreadcrumbItemResponse] = Field(default_factory=list)


# ---------------------------------------------------------
# Request schemas
# ---------------------------------------------------------

class CreateTabRequest(StrictRequestModel):
    title: StrictStr = Field(
        min_length=1,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    parentDocumentId: StrictStr | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        pattern=CLEAN_DOCUMENT_ID_PATTERN,
    )

    content: dict[str, Any] | list[Any] | None = None

    order: int | None = Field(
        default=None,
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    # IMPORTANT:
    # The frontend sends inherited access_control when creating a tab.
    # Without this field, FastAPI rejects the request with 422.
    access_control: AccessControlResponse | dict[str, Any] | None = None

    # Which nav tab a new ROOT tab belongs to. Ignored for a sub-tab create
    # (parentDocumentId set) — sub-tabs have no nav_tab_id of their own. When
    # absent for a root create, the router falls back to the Dashboard nav
    # tab so any existing caller keeps working unchanged.
    navTabDocumentId: StrictStr | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        pattern=CLEAN_DOCUMENT_ID_PATTERN,
    )

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class UpdateTabRequest(StrictRequestModel):
    """NO `locked` / `locked_by` FIELDS — DELIBERATELY, NOT AN OVERSIGHT.

    plan_access_control_algorithm_2026-08-27.md §6.6 Fix 1 calls this the
    "third door": `update_tab_by_document_id_v2` used to accept these two
    fields and write them straight onto the row with NO ownership check at
    all — a client could set `{locked: true, locked_by: "anyone"}` on any
    root tab, or silently clear someone else's lock, without going near
    `PUT .../lock` or `PUT .../unlock`.

    Removed outright rather than accepted-and-ignored: `StrictRequestModel`
    is `extra="forbid"`, so a client that still sends either field now gets
    a 422 — the loud failure this door needs, matching how `LockTabRequest`
    / `UnlockTabRequest` below dropped their own client-supplied identity
    fields for the same reason. Nothing in the frontend ever sent these
    (verified against every `updateTab`/`updateTabV2` call site), so this
    is uncoupled from the frontend change those two request classes require.

    Locking stays reachable only through `PUT .../lock` and
    `PUT .../unlock`, which derive the holder from the authenticated
    identity — never from a request body — and which still refuse a nested
    gridstack (hazard 4)."""

    title: StrictStr | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    order: int | None = Field(
        default=None,
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    access_control: AccessControlResponse | dict[str, Any] | None = None

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class CreateTabVariantRequest(StrictRequestModel):
    title: StrictStr = Field(
        min_length=1,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    access_control: AccessControlResponse | dict[str, Any] | None = None

    order: int | None = Field(
        default=None,
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class ReorderTabVariantsRequest(StrictRequestModel):
    orderedDocumentIds: list[StrictStr] = Field(default_factory=list)


class MoveTabRequest(StrictRequestModel):
    newParentDocumentId: StrictStr | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        pattern=CLEAN_DOCUMENT_ID_PATTERN,
    )

    order: int | None = Field(
        default=None,
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class ReorderTabItemRequest(StrictRequestModel):
    documentId: StrictStr = Field(
        min_length=1,
        max_length=255,
        pattern=CLEAN_DOCUMENT_ID_PATTERN,
    )

    order: int = Field(
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class ReorderTabsRequest(StrictRequestModel):
    items: list[ReorderTabItemRequest] = Field(min_length=1)


class UpdateTabContentRequest(StrictRequestModel):
    content: dict[str, Any] | list[Any] | None = None


class UpdateComponentContentRequest(StrictRequestModel):
    """Body of the per-component content write (§6.7 of
    plan_access_control_algorithm_2026-08-27.md).

    Partial: only the fields actually present are applied — the router reads
    `model_fields_set` — so a caller can rename a widget without resending
    its whole data blob.

    WHAT IS ABSENT IS THE INTERESTING PART, and `extra="forbid"` (inherited
    from StrictRequestModel) is what makes the absences enforceable rather
    than merely conventional:

      * `x`/`y`/`w`/`h` — repositioning is DELIBERATELY not implemented;
        §11.3 defers it pending team discussion.
      * `access_control` — authorization, not content. Grants are edited
        through the grants surface, which has its own gate (§6.3).
      * `type`, `link` — a type change re-interprets the stored blob, and
        `type` is the only route by which the `restricted` redaction
        sentinel could reach `components.type`. A client that posts a whole
        serialized widget entry therefore gets a 422 instead of a partial
        write, which is the intended outcome: that body was built for the
        canvas save, and the canvas save is exactly what §6.7 says a
        component-scoped editor must not use.

    See `gridstack_service.update_component_content` for the full rationale.
    """

    title: StrictStr | None = Field(default=None, max_length=255)
    description: StrictStr | None = None

    # Nullable in the ANNOTATION so an absent key is representable, but an
    # EXPLICIT null is refused below. See `_reject_explicit_null_data`.
    data: dict[str, Any] | None = None

    @model_validator(mode="after")
    def _reject_explicit_null_data(self) -> "UpdateComponentContentRequest":
        """`data: null` is a 422, while an omitted `data` means "leave it
        alone" and `data: {}` means "empty this widget".

        THIS IS THE SECOND HALF OF THE SENTINEL GUARD. A widget the caller
        may not see is served as `{"type": "restricted", "data": null}`
        (tab_service.py:100), and that entry KEEPS ITS KEY, so it round-trips
        through a stale client and comes back on the next save. `type` is
        already refused by `extra="forbid"`; `data: null` is the other half
        of that same body. Accepting it would overwrite a real widget's
        stored content with `{}` — the precise data-loss path the canvas save
        was fixed for on 2026-08-30, rebuilt on a new door.

        Refusing rather than ignoring, because unlike the canvas save there
        is nothing to degrade gracefully FOR here: this endpoint edits one
        component the caller named explicitly, so a null blob is a
        malformed request about that component, not an incidental sibling
        entry that can be skipped. "Clear this widget" stays expressible as
        `data: {}`.
        """
        if "data" in self.model_fields_set and self.data is None:
            raise ValueError(
                "data must be an object; send {} to empty the widget, or omit "
                "the field to leave it unchanged"
            )
        return self


class LockTabRequest(StrictRequestModel):
    """NO `locked_by` FIELD — DELIBERATELY, NOT AN OVERSIGHT.

    plan_access_control_algorithm_2026-08-27.md §6.6 Fix 1: `locked_by` used
    to be a required client-supplied string, compared verbatim against the
    stored holder — so a lock could be taken over by sending the right name.
    The router already authenticates every request (`get_current_user`); it
    simply never used who the caller actually was. Removed rather than
    accepted-and-ignored: `StrictRequestModel` is `extra="forbid"`, so a
    client that still sends the field now gets a 422 — the loud failure
    intended here, not a silent ignore.

    Owner's decision, 2026-09-02 (carried into the 2026-09-03 locking
    session): both `renphil-hub-backend` and `renphil-hub-frontend` change
    in the same session and deploy together, so there is no transitional
    accept-and-ignore period — the field is gone outright on both sides.
    Shipping only one half is a 422 on every lock.

    `force` — NEW, plan_lock_propagation_2026-09-08.md §4.2 decision 8.
    Takes over `document_id`'s whole subtree in one transaction when
    something in it is held fresh by someone else, instead of refusing —
    replacing the old unlock(force) -> lock two-step, which had a real race
    (someone else could grab the node between the two calls). Does NOT
    reopen Fix 1 above: `force` is not an identity field, `locked_by` stays
    JWT-derived. Body is now `{}` or `{"force": true}`."""

    force: StrictBool = False


class UnlockTabRequest(StrictRequestModel):
    """NO `unlocked_by` FIELD — same reasoning as `LockTabRequest` above,
    PLUS it closes a second, undocumented bypass by construction.

    `unlocked_by` used to be OPTIONAL (`str | None = None`), and the
    ownership check in `unlock_tab_by_document_id_v2` was
    `... and unlocked_by and ...` — a caller that omitted the field (or sent
    `null`) short-circuited that check to `False` and the unlock proceeded
    with NO ownership check at all. `force: true` was never required to
    steal a lock; simply not sending `unlocked_by` was an equally effective,
    entirely undocumented way in. Removing the field closes this
    structurally: an identity that cannot be supplied by the client cannot
    be omitted by the client either — the server derives it from the JWT on
    every call, with nothing left for an absent/null value to short-circuit.

    `force` is UNCHANGED (owner decision, 2026-09-03): still present, still
    unrestricted — see `unlock_tab_by_document_id_v2`'s docstring in
    gridstack_service.py for why."""

    force: StrictBool = False


# ---------------------------------------------------------
# Nav tab request schemas
# ---------------------------------------------------------

class CreateNavTabRequest(StrictRequestModel):
    title: StrictStr = Field(
        min_length=1,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    access_control: AccessControlResponse | dict[str, Any] | None = None

    order: int | None = Field(
        default=None,
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    icon: StrictStr | None = Field(default=None, max_length=64, pattern=ICON_NAME_PATTERN)

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class UpdateNavTabRequest(StrictRequestModel):
    title: StrictStr | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        pattern=CLEAN_TEXT_PATTERN,
    )

    order: int | None = Field(
        default=None,
        ge=MIN_ORDER_VALUE,
        le=MAX_ORDER_VALUE,
    )

    access_control: AccessControlResponse | dict[str, Any] | None = None

    # Three-way, like the airtable `pat` field: omitted (leave alone, checked
    # via model_fields_set at the router) vs. present-and-a-string (set) vs.
    # present-and-null (clear to the default icon — §3.4's "Use default").
    icon: StrictStr | None = Field(default=None, max_length=64, pattern=ICON_NAME_PATTERN)

    @field_validator("order", mode="before")
    @classmethod
    def validate_order(cls, value: Any) -> Any:
        return validate_order_not_bool(value)


class ReorderNavTabsRequest(StrictRequestModel):
    orderedDocumentIds: list[StrictStr] = Field(default_factory=list)


class MoveTabToNavTabRequest(StrictRequestModel):
    navTabDocumentId: StrictStr = Field(
        min_length=1,
        max_length=255,
        pattern=CLEAN_DOCUMENT_ID_PATTERN,
    )
